# Generated by Django 4.1.3 on 2022-12-21 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publishedmanager_remove_post_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
