# Generated by Django 4.1.3 on 2022-12-27 12:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_publishedmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
